// Auto-generated shader sources

const char* fragment_src = "#version 430 core\n"
"precision highp float;\n"
"in vec2 uv;\n"
"out vec4 FragColor;\n"
"\n"
"#define CHUNK_SIZE 64\n"
"#define CHUNK_SIZE_FLOAT 64.0\n"
"#define CHUNK_BSHIFT 6\n"
"#define CHUNK_MASK 0x3F\n"
"\n"
"uniform float camera_position_x;\n"
"uniform float camera_position_y;\n"
"uniform float camera_zoom;\n"
"uniform float aspect_ratio;\n"
"\n"
"uniform uint chunk_array_size;\n"
"\n"
"uniform int spatial_access_grid_x;\n"
"uniform int spatial_access_grid_y;\n"
"uniform int spatial_access_grid_w;\n"
"uniform int spatial_access_grid_l;\n"
"\n"
"uniform usampler2DArray chunk_array;\n"
"uniform sampler2DArray tile_textures;\n"
"\n"
"struct chunk_entry {\n"
"    int  chunk_array_index;\n"
"    int  chunk_status;\n"
"    uint nbt_ptr_low;\n"
"    uint nbt_ptr_high;\n"
"\n"
"    int _pad0;\n"
"    int _pad1;\n"
"    int _pad2;\n"
"    int _pad3;\n"
"};\n"
"\n"
"layout(std140, binding = 0) uniform sag {\n"
"    chunk_entry spatial_access_grid[64];\n"
"};\n"
"\n"
"int signed_rshift(int a, int shift) {\n"
"    return (a + ((a >> 31) & ((1 << shift) - 1))) >> shift;\n"
"}\n"
"\n"
"void main() {\n"
"    vec2 camera_position = vec2(camera_position_x, camera_position_y);\n"
"\n"
"    // convert pixel uv to world tile coords\n"
"    vec2 world = camera_position + (uv - 0.5) * vec2(aspect_ratio * camera_zoom, camera_zoom);\n"
"    ivec2 tile = ivec2(floor(world));\n"
"    vec2 tile_uv = fract(world);\n"
"    ivec2 chunk = ivec2(floor(world / CHUNK_SIZE_FLOAT));\n"
"\n"
"    bool is_valid_chunk = chunk.x >= spatial_access_grid_x && chunk.x < spatial_access_grid_x + spatial_access_grid_w &&\n"
"                          chunk.y >= spatial_access_grid_y && chunk.y < spatial_access_grid_y + spatial_access_grid_l;\n"
"    \n"
"    // Still need to fix artifact that occurs when loading a new chunk.\n"
"    if(!is_valid_chunk) {\n"
"        FragColor = vec4(1.0, 0.0, 0.0, 1.0);\n"
"        return;\n"
"    }\n"
"\n"
"    int sag_index = (chunk.x - spatial_access_grid_x) + \n"
"                    (chunk.y - spatial_access_grid_y) * spatial_access_grid_w;\n"
"\n"
"    // lookup the chunk and intra-chunk tile coords\n"
"    int chunk_index = spatial_access_grid[sag_index].chunk_array_index;\n"
"    int chunk_status = spatial_access_grid[sag_index].chunk_status;\n"
"\n"
"    //is_valid_chunk = chunk_status == 1;\n"
"    //if (!is_valid_chunk) {\n"
"    //    FragColor = vec4(1.0, 1.0, 0.0, 1.0);\n"
"    //    return;\n"
"    //}\n"
"\n"
"    ivec2 local = ivec2(mod(tile.x, CHUNK_SIZE), mod(tile.y, CHUNK_SIZE));\n"
"\n"
"    // read the tile ID\n"
"    uvec4 tile_id_vec4 = texelFetch(chunk_array, ivec3(local.x, local.y, chunk_index), 0);\n"
"    uint tile_id = tile_id_vec4.r;\n"
"\n"
"    // sample tile sprite\n"
"    FragColor = texture(tile_textures, vec3(tile_uv, int(tile_id)));\n"
"    //FragColor = vec4(local / CHUNK_SIZE_FLOAT, 0.0, 1.0);\n"
"}";

const char* vertex_src = "#version 330 core\n"
"layout(location = 0) in vec2 aPos;\n"
"\n"
"out vec2 uv;\n"
"\n"
"void main() {\n"
"    uv = (aPos + 1.0) * 0.5; // map [-1, 1] → [0, 1]\n"
"    gl_Position = vec4(aPos, 0.0, 1.0);\n"
"}\n"
"";

