// Auto-generated shader sources

const char* fragment_src = "#version 430 core\n"
"precision highp float;\n"
"in vec2 uv;\n"
"out vec4 FragColor;\n"
"\n"
"uniform float camera_position_x;\n"
"uniform float camera_position_y;\n"
"uniform float camera_zoom;\n"
"uniform float aspect_ratio;\n"
"\n"
"layout(std430, binding = 0) buffer ChunkData {\n"
"    uint tile_data[]; // Technically are packed 16-bit integers. Must use bit operations to extract from 32-bit.\n"
"};\n"
"\n"
"uint get_tile_id(uint index) {\n"
"    uint pair = tile_data[index / 2u];\n"
"    if ((index & 1u) == 0u)\n"
"        return pair & 0xFFFFu;\n"
"    else\n"
"        return pair >> 16;\n"
"}\n"
"\n"
"void main() {\n"
"    vec2 camera_position = vec2(camera_position_x, camera_position_y);\n"
"    \n"
"    // camera_pos + (uv - 0.5) * vec2(aspect * zoom, zoom)\n"
"\n"
"    vec2 tile_coordinates = camera_position + (uv - 0.5) * vec2(aspect_ratio * camera_zoom, camera_zoom);\n"
"\n"
"    int tile = int(mod(floor(tile_coordinates.x) + floor(tile_coordinates.y), 2.0));\n"
"\n"
"    if (tile == 0) {\n"
"        FragColor = vec4(0.0, 0.0, 0.0, 1.0);\n"
"    } else {\n"
"        FragColor = vec4(1.0, 0.0, 0.0, 1.0);\n"
"    }\n"
"}\n"
"";

const char* vertex_src = "#version 330 core\n"
"layout(location = 0) in vec2 aPos;\n"
"\n"
"out vec2 uv;\n"
"\n"
"void main() {\n"
"    uv = (aPos + 1.0) * 0.5; // map [-1, 1] → [0, 1]\n"
"    gl_Position = vec4(aPos, 0.0, 1.0);\n"
"}\n"
"";

